services:
  database:
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy
volumes:
  pg_data:

networks:
  internal:
